### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by heath-freenome** [mokkabonna/json-schema-merge-allof#38]
It seems like the last commit was over a year ago. We are actively using this library and would hate to see it no longer being active. Please let us know whether we can expect more support.

**Comment by mokkabonna** [comment]
Yes it is being supported. It was however written for draft 6 and it might not consider all of the new keywords in later versions.

I do also plan to get it up to date with the latest version.

However with the use of custom resolvers I think most of the new keywords can be added by the end user if needed. 

Let me know if there are any bugs for your use case.

**Comment by mokkabonna** [comment]
As long as you don't use a defaultresolver it will fail when it encounters keywords it does not understand. So that should force you to have a resolver if you are using newer keywords. So either you are already using custom resolvers(?) or are not using keywords that are newer. 

If you are using custom resolvers for newer keywords, I'd be happy to incorporate them as part of the planned update to new json schema version.
